#!/bin/sh

# aliases
alias ls='ls -GFh'
alias py='ipython3'
alias gitlazy='git add -A; git commit -am.; git push'
alias t0='tmux a -t0'
alias t1='tmux a -t1'

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='vim'
# fi

# Sdkman
# export SDKMAN_DIR="/Users/gio/.sdkman"
# [[ -s "/Users/gio/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/gio/.sdkman/bin/sdkman-init.sh"

# Pants
alias pants-check="pants list --changed-since=HEAD fmt lint && pants check --changed-since=HEAD --changed-dependents=transitive"
alias pants-check-master="pants list --changed-since=origin/master fmt lint && pants check --changed-since=origin/master --changed-dependents=transitive"
export PANTS_CONCURRENT=False

export PATH=$HOME/bin/:$PATH
export PATH=/opt/homebrew/bin:$PATH
export CHROMIUM_EXECUTABLE_PATH="~/Library/Caches/ms-playwright/chromium-1200/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing"
